"""Add new_column to Album

Revision ID: 2b98b8076f83
Revises: 
Create Date: 2023-09-30 15:47:58.476287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b98b8076f83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('release_year', sa.Integer(), nullable=True))
    op.add_column('albums', sa.Column('album_scraped_id', sa.Integer(), nullable=True))
    op.add_column('albums', sa.Column('artist_scraped_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'artist_scraped_id')
    op.drop_column('albums', 'album_scraped_id')
    op.drop_column('albums', 'release_year')
    # ### end Alembic commands ###
